sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker
before_install:
  - docker build -t dockerbuild/newbuild -f Dockerfile.dev .
script:
  - docker run -e CI=true dockerbuild/newbuild npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "dockkp123"
  env: "Dockkp123-env"
  bucket_name: "elasticbeanstalk-ap-south-1-701994403871"
  bucket_path: "dockerkplearning-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
